# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: continuous-integration
env:
  USE_JAVA_DISTRIBUTION: 'zulu'
  USE_JAVA_VERSION: '25'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  # On main branch, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master') && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  maven-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [25]
        # Additionally add macos & windows with a single recent JDK
        include:
          - os: macos-latest
            java: 25
          # Windows has some line-ending issues right now.
          #- os: windows-latest
          #  java: 17
      fail-fast: false
      max-parallel: 4
    name: Test using Maven with JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/actions/maven-test

  local-artifact-tests:
    runs-on: ubuntu-latest
    name: Local Artifact Tests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/actions/local-artifact-tests
